<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Automation-PC" name="suiteTest.Regresion_Medico" tests="11" failures="1" timestamp="19 jul 2019 13:46:17 GMT" time="586.244" errors="0">
  <testcase name="M_Home_04" time="27.636" classname="suiteTest.Regresion_Medico"/>
  <testcase name="M_Login_03" time="11.254" classname="suiteTest.Regresion_Medico"/>
  <testcase name="M_Login_01" time="5.972" classname="suiteTest.Regresion_Medico"/>
  <testcase name="M_Home_02" time="20.527" classname="suiteTest.Regresion_Medico"/>
  <testcase name="M_Login_05" time="9.699" classname="suiteTest.Regresion_Medico"/>
  <testcase name="M_Home_05" time="242.430" classname="suiteTest.Regresion_Medico">
    <failure type="java.lang.AssertionError" message="Fallo test - M_Home_05 - Step: 2_Se verifica la visualizaci贸n del bot贸n Salir">
      <![CDATA[java.lang.AssertionError: Fallo test - M_Home_05 - Step: 2_Se verifica la visualizaci贸n del bot贸n Salir
	at org.testng.Assert.fail(Assert.java:93)
	at steps.M_Home_SalirStep.Run(M_Home_SalirStep.java:54)
	at suiteTest.Regresion_Medico.M_Home_05(Regresion_Medico.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- M_Home_05 -->
  <testcase name="M_Login_02" time="20.174" classname="suiteTest.Regresion_Medico"/>
  <testcase name="M_Login_04" time="6.806" classname="suiteTest.Regresion_Medico"/>
  <testcase name="M_Login_06" time="11.461" classname="suiteTest.Regresion_Medico"/>
  <testcase name="M_Home_01" time="58.656" classname="suiteTest.Regresion_Medico"/>
  <testcase name="M_Home_03" time="171.629" classname="suiteTest.Regresion_Medico"/>
</testsuite> <!-- suiteTest.Regresion_Medico -->
